### ISSUE TITLE
Implementation for iOS

### ISSUE THREAD

**Issue by DawieLombaard** [manojdcoder/nativescript-mrz-reader#3]
I need an implementation for iOS, and in your readme you specify "npm run demo.ios", however there doesn't seem to be any implementation for iOS?

Has this implementation not been done, or does the git repo just not include it?

**Comment by manojdcoder** [comment]
@DawieLombaard no iOS is not implemented.

**Comment by DawieLombaard** [comment]
Thanks for the update.
